config/routes.rb
Rails.application.routes.draw do

  resources :ingredients
  resources :foods
  resources :sports
  resources :sufferings
  resources :recommendations
  resources :countries
  resources :registrations
  resources :people
  devise_for :users, :controller => {sessions: 'sessions' }

  get 'pages/index'
  get 'pages/form'
  get 'pages/feeding'
  get 'pages/sports_page'

  root 'pages#index'
  get '/feeding', to: 'pages#feeding', as: 'feeding'
  get '/sports_page', to: 'pages#sports', as: 'sportss'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :country

  # validaciones

  validates :height, presence: true
  validates :weight, presence: true
  validates :age, presence: true
  validates :country_id, presence: true
  validates :abdominal_perim, presence: true
  validates :age, presence: true

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  $countries
  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    $sufferings = Suffering.all
    @bmi = Bmi.new(@person.weight,@person.age,@person.height,@person.sex)
  end

  # GET /people/new
  def new
    $countries = Country.all
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
    $countries = Country.all
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    if
      respond_to do |format|
        if @person.save
          format.html { redirect_to @person, notice: 'Datos Guardados exitosamente.'}
          format.json { render :show, status: :created, location: @person }
        else
          format.html { render :new }
          format.json { render json: @person.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:height, :weight, :age, :abdominal_perim, :sex, :country_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "form-group">
    <%= form.label :height,"Altura", :class => "control-label"%>
    <%= form.text_field :height, placeholder: "Digite su altura en metros", id: :person_height, :class => "form-control" %>
  </div>

  <div class = "form-group">
    <%= form.label :weight,"Peso", :class => "control-label"%>
    <%= form.text_field :weight, placeholder: "Digite su peso en kilogramos", id: :person_weight, :class => "form-control" %>
  </div>

  <div class = "form-group">
    <%= form.label :country_id,"Selecione su país de origen", :class => "control-label"%><br>
    <%= form.select :country_id, options_from_collection_for_select($countries,"id", "name"), :class => "form-control" %>
  </div>
  <div class = "form-group">
    <%= form.label :abdominal_perim,"Perímetro abdominal", :class => "control-label"%>
    <%= form.text_field :abdominal_perim, placeholder: "Digite su perímetro abdominal en decimal", id: :person_abdominal_perim, :class => "form-control"%>
  </div>

  <div class = "form-group">
    <%= form.label :age,"Edad", :class => "control-label"%>
    <%= form.text_field :age, id: :person_age, :class => "form-control" %>
  </div>

  <div class = "form-group">
    <%= form.label :sex ,"Defina su Sexo", :class => "control-label"%><br>
    <%= form.label :sex ,"masculno", :class => "control-label"%>&nbsp;
    <%= form.radio_button :sex ,"1"%>&nbsp;&nbsp;
    <%= form.label :sex ,"femenino", :class => "control-label"%>&nbsp;
    <%= form.radio_button :sex ,"2"%>
  </div>

  <div class="form-group">
    <%= form.submit 'Calcular IMC', :class => "btn btn-primary"%>
    <%= link_to 'Volver', people_path, :class => "btn btn-danger"%>
  </div>
<% end %>

app/views/people/edit.html.erb
<br>
<h3 align="center">Salud y Bienestar</h3>
<div class="content">
  <div class="box box-info">
    <div class="box-header">
      <h2 class="box-title">Editar datos del formulario</h2>
    </div>
    <div class="box-body">
      <div id="content-form" class="row">
        <div class="col-md-6">
          <%= render 'form', person: @person %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Height</th>
      <th>Weight</th>
      <th>Abdominal perim</th>
      <th>Imc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <% if !person.country.nil? %>
        <tr>
          <td><%= person.height %></td>
          <td><%= person.weight %></td>
          <td><%= person.abdominal_perim %></td>
          <td><%= person.country.name %></td>
          <td><%= link_to 'Show', person %></td>
          <td><%= link_to 'Edit', edit_person_path(person) %></td>
          <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<br>
<h3 align="center">Salud y Bienestar</h3>
<div class="content">
  <div class="box box-info">
    <div class="box-header">
      <h2 class="box-title">Calcular el Indice de Masa Corporal</h2>
    </div>
    <div class="box-body">
      <div id="content-form" class="row">
        <div class="col-md-6">

          <%= render 'form', person: @person %>

        </div>
        <div class="col-lg-6 image-form">
          <h3>Alimentación balanceada</h3>
          <%= image_tag "foods.jpg"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/people/show.html.erb
<h3 align="center">Salud y Bienestar</h3>

<div class="content">
  <p class="notice"><%= notice %></p>
  <div class="box box-info">
    <div class="box-header">
      <h2 class="box-title">Datos ingresados al formulario</h2>
    </div>
    <div class="box-body">
      <div id="content-form" class="row">
        <div class = "form-group">
          <strong>Altura: </strong>
          <%= @person.height %>
        </div>

        <div class = "form-group">
          <strong>Peso:</strong>
          <%= @person.weight %>
        </div>

        <div class = "form-group">
          <strong>Perímetro abdominal: </strong>
          <%= @person.abdominal_perim %>
        </div>

        <div class = "form-group">
          <strong>Edad:</strong>
          <%= @person.age %>
        </div>
        <div class = "form-group">
          <strong>País:</strong>
          <%= @person.country.name %>
        </div>
      </div>
    </div>
  </div>

  <% if @bmi.show_code == @bmi.get_code_normopeso %>
    <div class = "box box-success form-group has-success">
      <label class="control-list" for="inputSuccess"><i class="fa fa-check">&nbsp; Resultado</i></label>
      <label class="control-list" for="inputSuccess"><%= @bmi.show_result%></label>
    </div>
  <% elsif @bmi.show_code == @bmi.get_code_obesity ||
      @bmi.show_code == @bmi.get_code_under_weight %>
    <div class = "box box-danger form-group has-error">
      <label class="control-list" for="inputError"><i class="fa fa-warning">&nbsp; Resultado</i></label>
      <label class="control-list" for="inputError"><%= @bmi.show_result%></label>
    </div>

  <%	elsif @bmi.show_code == @bmi.get_code_overweight %>
    <div class = "box box-warning form-group has-warning">
      <label class="control-list" for="inputWarning"><i class="fa fa-warning">&nbsp; Resultado</i></label>
      <label class="control-list" for="inputWarning"><%= @bmi.show_result%></label>
    </div>
  <% end %>

  <div class="box box-info">
    <div class="box-header">
      <h2 class="box-title">Recomendaciones</h2>
    </div>
    <div class="box-body">

      <% $sufferings.each do |suf| %>
<<<<<<< HEAD
        <%  if suf.code == 0 %>

          <strong class="subtitle text-muted">Puede practicar los siguentes deportes:</strong>
=======
        <%  if suf.code == @bmi.show_code %>
          <strong class="subtitle text-muted">Puede practicar los siguentes deportes:</strong> <br> <br>
>>>>>>> 8e380037f7b707ac4802cb85b4a7638323af1386
          <% suf.sports.each do |spt|  %>
            <div class="card">
              <div class="row">
                <div class="col-md-3">
                  <%= image_tag(spt.url_img, size: "700x700", alt: "Error al cargar la imagen")	%>
                </div>

                <div class="col-md-9">
                  <div class="card-body">
                    <h5 class="card-title title_card"><%= spt.name %></h5> <br>
                    <p class="card-text"><%= spt.description %></p>
                  </div>
                </div>
              </div>
            </div>
          <%	end  %>

          <strong class="subtitle text-muted">Para su estado, le recomendamos los siguientes alimentos:</strong> <br> <br>
            <% suf.foods.each do |food|  %>
              <div class="card">
                <div class="row">
                  <div class="col-md-3">
                    <%= image_tag(spt.url_img, size: "700x700", alt: "Error al cargar la imagen")	%>
                  </div>

                  <div class="col-md-9">
                    <div class="card-body">
                      <h5 class="card-title title_card"><%= food.name %></h5> <br>
                      <p class="card-text"><%= food.description %></p>
                    </div>
                  </div>
                </div>
              </div>

          <% end %>
        <%	end  %>
      <% end %>
    </div>
  </div>

</div>
<div class="content">
  <%= link_to 'Modificar información', edit_person_path(@person), :class => "btn btn-primary" %>
  <%= link_to 'Volver al inicio', pages_index_path, :class => "btn btn-danger" %>
</div>