config/routes.rb
Rails.application.routes.draw do

  resources :ingredients
  resources :foods
  resources :sports
  resources :sufferings
  resources :recommendations
  resources :countries
  resources :registrations
  resources :people
  devise_for :users, :controller => {sessions: 'sessions' }

  get 'pages/index'
  get 'pages/form'
  get 'pages/feeding'
  get 'pages/sports_page'

  root 'pages#index'
  get '/feeding', to: 'pages#feeding', as: 'feeding'
  get '/sports_page', to: 'pages#sports', as: 'sportss'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sport.rb
class Sport < ApplicationRecord
  belongs_to :suffering

  validates :acceptance, presence: true
  validates :description, presence: true
  validates :name, presence: true
  validates :url_img, presence: true

end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]
  $suffering
  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
    
  end

  # GET /sports/new
  def new
    @sport = Sport.new
    $suffering = Suffering.all
  end

  # GET /sports/1/edit
  def edit
    $suffering = Suffering.all
  end

  # POST /sports
  # POST /sports.json
  def create

    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Deporte guardado exitosamente' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Deporte modificado exitosamente.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Deporte eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_params
      params.require(:sport).permit(:description, :url_img, :name, :acceptance, :suffering_id)
    end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_with(model: sport, local: true) do |form| %>
  <% if sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :sport_description %>
  </div>

  <div class="field">
    <%= form.label :url_img %>
    <%= form.text_field :url_img, id: :sport_url_img %>
  </div>

  <!--Mi nuevo código del combobox-->
  <div class = "form-group">
    <%= form.label :suffering_id, "Padecimiento asociado", :class => "control-label"%><br>
    <%= form.select :suffering_id, options_from_collection_for_select($suffering,"id", "name"), :class => "form-control" %>
  </div>
  <!--Fin de mi código-->

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :sport_name %>
  </div>

  <div class="field">
    <%= form.label :acceptance %>
    <%= form.number_field :acceptance, id: :sport_acceptance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing Sport</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deportes</h1>

<table>
  <thead>
    <tr>
      <th>Descripción</th>
      <th>Url img</th>
      <th>Nombre</th>
      <th>Acceptance </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
    <% @sports.each do |sport| %>
      <tr>
        <td><%= sport.description %></td>
        <td><%= sport.url_img %></td>
        <td><%= sport.name %></td>
        <td><%= sport.acceptance %></td>
        
        <td><%= link_to 'Show', sport %></td>
        <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
        <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>Nuevo deporte</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripción:</strong>
  <%= @sport.description %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @sport.url_img %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @sport.name %>
</p>


<p>
  <strong>Votos:</strong>
  <%= @sport.acceptance %>
</p>

<%= link_to 'Editar', edit_sport_path(@sport) %> |
<%= link_to 'Atrás', sports_path %>