config/routes.rb
Rails.application.routes.draw do

  resources :ingredients
  resources :foods
  resources :sports
  resources :sufferings
  resources :recommendations
  resources :countries
  resources :registrations
  resources :people
  devise_for :users, :controller => {sessions: 'sessions' }

  get 'pages/index'
  get 'pages/form'
  get 'pages/feeding'
  get 'pages/sports_page'

  root 'pages#index'
  get '/feeding', to: 'pages#feeding', as: 'feeding'
  get '/sports_page', to: 'pages#sports', as: 'sportss'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :food
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :api_code)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ingredient_name %>
  </div>

  <div class="field">
    <%= form.label :api_code %>
    <%= form.text_field :api_code, id: :ingredient_api_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Api code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.api_code %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Api code:</strong>
  <%= @ingredient.api_code %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>