config/routes.rb
Rails.application.routes.draw do

  resources :ingredients
  resources :foods
  resources :sports
  resources :sufferings
  resources :recommendations
  resources :countries
  resources :registrations
  resources :people
  devise_for :users, :controller => {sessions: 'sessions' }

  get 'pages/index'
  get 'pages/form'
  get 'pages/feeding'
  get 'pages/sports_page'

  root 'pages#index'
  get '/feeding', to: 'pages#feeding', as: 'feeding'
  get '/sports_page', to: 'pages#sports', as: 'sportss'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nutri-A | Inicio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <% if @controller != "index" %>
      <%= stylesheet_link_tag 'application.page', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>

  </head>

  <body>
    <!--Header-->
    <header class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <%= image_tag 'logo.png',:class => "pull-left"%>
                <div class="nav-collapse collapse pull-right">
                    <ul class="nav">
                      <li><%= link_to "Salud y Bienestar", new_person_path%></li>
                      <li><%= link_to "Alimentación", pages_feeding_path%></li>
<<<<<<< HEAD
                      <li><%= link_to "Deportes", sports_path%></li>
                      <li><%= link_to "Inico", pages_index_path%></li>
                      <li><%= link_to "padecimientos", sufferings_path%></li>
                      
=======
                      <li><%= link_to "Deportes", pages_sports_path%></li>
                      <li><%= link_to "Blog"%></li>
                      <li><%= link_to "Contacto"%></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages <i class="icon-angle-down"></i></a>
                        <ul class="dropdown-menu">
                          <li><a href="career.html">Career</a></li>
                          <li><a href="blog-item.html">Blog Single</a></li>
                          <li><a href="faq.html">FAQ</a></li>
                          <li><a href="pricing.html">Pricing</a></li>
                          <li><a href="404.html">404</a></li>
                          <li><a href="typography.html">Typography</a></li>
                          <li><a href="registration.html">Registration</a></li>
                          <li class="divider"></li>
                          <li><a href="privacy.html">Privacy Policy</a></li>
                          <li><a href="terms.html">Terms of Use</a></li>
                        </ul>
                      </li>
>>>>>>> a61634594d694ab4e6a08b0a2d3d5c0cd82cec34
                      <li class="login">
                        <a data-toggle="modal" href="#loginForm">
                          <i class = "fa fa-lock"></i></a>
                      </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </header>
    <!-- /header -->
    <%= yield %>
    <!--Scripts of js-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Descarga pendiente-->
    <script src= "//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-hover-dropdown/2.2.1/bootstrap-hover-dropdown.min.js"></script>
  </body>
</html>